---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[sensu::default]
      - recipe[sensu::redis]
      - recipe[sensu::rabbitmq]
      - recipe[sensu::server_service]
      - recipe[sensu::api_service]
    attributes:

